apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: json-server-app # application name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/srankmeng/my-gitops.git'
    path: k8s # directory keep k8s manifest files
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true # auto delete resource when haven't on git repository
      selfHeal: true # auto sync state compare on git repository